# Generated by Django 2.2.16 on 2020-12-04 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpesapay',
            name='cash',
        ),
    ]
