# Generated by Django 2.2.16 on 2020-12-04 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_remove_mpesapay_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesapay',
            name='cash',
            field=models.BooleanField(default=False),
        ),
    ]
