# Generated by Django 2.0.13 on 2020-03-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default="In this series we're going to be building an Ecommerce website with Django. This video shows how "),
            preserve_default=False,
        ),
    ]
