# Generated by Django 2.2.16 on 2020-12-06 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_mpesapay_cash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesapay',
            name='cash',
            field=models.CharField(default='notpayed', max_length=15),
        ),
    ]
