# Generated by Django 2.2.16 on 2021-01-17 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_auto_20201206_0507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
    ]
