# Generated by Django 2.0.13 on 2020-07-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_auto_20200702_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='refund',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
