# Generated by Django 2.0.13 on 2020-07-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_auto_20200718_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mpesapay',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
