# Generated by Django 2.0.13 on 2020-04-08 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0016_mpesapay'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mpesa_pay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shops.Mpesapay'),
        ),
    ]
