# Generated by Django 2.0.13 on 2020-04-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0019_auto_20200409_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
